title: InoS Heo's Blog
name: Your New Jekyll Site
pygments: true

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

paginate: 10
