title: Jason Heo's Blog
name: Your New Jekyll Site
highlighter: rouge

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

paginate: 10
